name: Bran Deployment

on:
  push:
    branches:
      - production
      - develop
  pull_request:
    branches:
      - production
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setting the image tag as an environment variable to use across steps
      - name: Set image tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/production" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=develop" >> $GITHUB_ENV
          fi

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/bran:$TAG

      - name: Publish the Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/bran:$TAG
