name: Bran production deployment

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setting the image tag as an environment variable to use across steps
      - name: Set image tag
        id: prep
        run: echo "::set-output name=tag::$(date +%s)"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/bran:${{ steps.prep.outputs.tag }}

      - name: Publish the Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/bran:${{ steps.prep.outputs.tag }}
